openapi: 3.0.1
info:
  title: Books
  description: API Definition of Books
  version: 1.0.0
servers:
- url: http://localhost:8290/Books
paths:
  /:
    post:
      responses:
        default:
          description: Default response
